import { TarotCard } from "@/modules/tarot-engine/types";

function buildImagePath(id: number, name: string, arcana: 'major' | 'minor', suit: string | null): string {
  const safeName = name.toLowerCase().replace(/[^a-z0-9]+/g, "-");
  if (arcana === "major") {
    const numPad = String(id).padStart(2, "0");
    return `/tarot/major/${numPad}-${safeName}.svg`;
  }
  return `/tarot/minor/${suit || "wands"}/${safeName}.svg`;
}

export const tarotCards: TarotCard[] = [
  // 22 Major Arcana
  {
    id: 0,
    name: 'The Fool',
    arcana: 'major',
    suit: null,
    number: 0,
    uprightMeaning: 'Beginnings, innocence, spontaneity, a free spirit.',
    reversedMeaning: 'Holding back, recklessness, risk-taking, naivety.',
    keywords: ['new beginnings', 'optimism', 'leap of faith', 'potential'],
    element: 'air',
    zodiacCorrespondence: 'Uranus',
    image: buildImagePath(0, 'The Fool', 'major', null),
    love: 'A spontaneous romance, open-hearted vulnerability, or embracing love without fear of the unknown.',
    career: 'Embarking on a fresh professional path, entrepreneurial ventures, or exploring unmapped opportunities.',
    finance: 'Willingness to take calculated financial risks, but requiring basic budgeting safeguards.',
    spirituality: 'A profound soul-awakening and trusting the universe on an unchartered spiritual journey.',
  },
  {
    id: 1,
    name: 'The Magician',
    arcana: 'major',
    suit: null,
    number: 1,
    uprightMeaning: 'Manifestation, resourcefulness, power, inspired action.',
    reversedMeaning: 'Manipulation, poor planning, untapped talents, illusion.',
    keywords: ['creation', 'willpower', 'desire', 'focus'],
    element: 'air',
    zodiacCorrespondence: 'Mercury',
    image: buildImagePath(1, 'The Magician', 'major', null),
    love: 'Clear mutual communication, passionate magnetism, and conscious co-creation in love.',
    career: 'Mastery over tools, effective leadership, and bringing innovative projects from vision to reality.',
    finance: 'Harnessing your skills and ideas to create lucrative, sustainable streams of income.',
    spirituality: 'Channeling higher wisdom into tangible earthly action: As above, so below.',
  },
  {
    id: 2,
    name: 'The High Priestess',
    arcana: 'major',
    suit: null,
    number: 2,
    uprightMeaning: 'Intuition, sacred knowledge, divine feminine, subconscious mind.',
    reversedMeaning: 'Secrets, disconnected from intuition, withdrawal and silence.',
    keywords: ['mystery', 'inner voice', 'spirituality', 'secrets'],
    element: 'water',
    zodiacCorrespondence: 'Moon',
    image: buildImagePath(2, 'The High Priestess', 'major', null),
    love: 'Deep soulful connection, emotional subtlety, and trusting your instincts about partners.',
    career: 'Working behind the scenes, strategic insight, and relying on discreet judgment over noise.',
    finance: 'Keep financial deliberations confidential; trust your inner sense on major transactions.',
    spirituality: 'Accessing hidden subconscious realms, vivid dreams, and mystical inner wisdom.',
  },
  {
    id: 3,
    name: 'The Empress',
    arcana: 'major',
    suit: null,
    number: 3,
    uprightMeaning: 'Femininity, beauty, nature, nurturing, abundance.',
    reversedMeaning: 'Creative block, dependence on others, smothering, emptiness.',
    keywords: ['motherhood', 'creation', 'fertility', 'sensuality'],
    element: 'earth',
    zodiacCorrespondence: 'Venus',
    image: buildImagePath(3, 'The Empress', 'major', null),
    love: 'Harmonious nurturing bond, emotional warmth, and mutual pampering in romance.',
    career: 'A fertile period for creative output, collaborative growth, and bountiful team rewards.',
    finance: 'Financial comfort, wise material investments, and enjoying the fruits of your labor.',
    spirituality: 'Deep connection with Mother Nature and grounding spirituality in sensory appreciation.',
  },
  {
    id: 4,
    name: 'The Emperor',
    arcana: 'major',
    suit: null,
    number: 4,
    uprightMeaning: 'Authority, establishment, structure, father figure.',
    reversedMeaning: 'Domination, excessive control, lack of discipline, inflexibility.',
    keywords: ['structure', 'control', 'paternity', 'discipline'],
    element: 'fire',
    zodiacCorrespondence: 'Aries',
    image: buildImagePath(4, 'The Emperor', 'major', null),
    love: 'A stable, protective, and dedicated partnership with clear shared boundaries.',
    career: 'Executive leadership, structural clarity, organizational milestones, and firm decision-making.',
    finance: 'Rigorous budgeting, disciplined resource management, and long-term financial security.',
    spirituality: 'Integrating spiritual discipline, daily routine, and moral integrity into daily life.',
  },
  {
    id: 5,
    name: 'The Hierophant',
    arcana: 'major',
    suit: null,
    number: 5,
    uprightMeaning: 'Spiritual wisdom, religious beliefs, conformity, tradition, institutions.',
    reversedMeaning: 'Personal beliefs, freedom, challenging the status quo, dogma.',
    keywords: ['tradition', 'education', 'religion', 'mentor'],
    element: 'earth',
    zodiacCorrespondence: 'Taurus',
    image: buildImagePath(5, 'The Hierophant', 'major', null),
    love: 'Traditional commitment, shared cultural values, or formalizing a romantic alliance.',
    career: 'Institutional recognition, mentorship from senior figures, and adherence to professional standards.',
    finance: 'Conventional, low-risk investment vehicles and consulting certified financial advisors.',
    spirituality: 'Studying sacred lineages, philosophical doctrines, and receiving lineage initiations.',
  },
  {
    id: 6,
    name: 'The Lovers',
    arcana: 'major',
    suit: null,
    number: 6,
    uprightMeaning: 'Love, harmony, relationships, values alignment, choices.',
    reversedMeaning: 'Self-love, disharmony, imbalance, misalignment of values.',
    keywords: ['partnership', 'union', 'choices', 'attraction'],
    element: 'air',
    zodiacCorrespondence: 'Gemini',
    image: buildImagePath(6, 'The Lovers', 'major', null),
    love: 'Soulmate synergy, profound mutual attraction, and aligned core moral values.',
    career: 'Important crossroad decision, finding an aligned business partner, or choosing your true vocation.',
    finance: 'Joint financial decisions requiring complete transparency and mutual agreement.',
    spirituality: 'Integration of sacred masculine and feminine polarities within the self.',
  },
  {
    id: 7,
    name: 'The Chariot',
    arcana: 'major',
    suit: null,
    number: 7,
    uprightMeaning: 'Control, willpower, success, action, determination.',
    reversedMeaning: 'Self-discipline, opposition, lack of direction, aggression.',
    keywords: ['victory', 'overcoming obstacles', 'drive', 'focus'],
    element: 'water',
    zodiacCorrespondence: 'Cancer',
    image: buildImagePath(7, 'The Chariot', 'major', null),
    love: 'Overcoming emotional hurdles together and steering the relationship toward a shared goal.',
    career: 'Triumph over competition, ambitious project delivery, and unstoppable momentum.',
    finance: 'Taking decisive control of expenditures and steering toward financial milestones.',
    spirituality: 'Harnessing conflicting internal impulses into a single directed spiritual path.',
  },
  {
    id: 8,
    name: 'Strength',
    arcana: 'major',
    suit: null,
    number: 8,
    uprightMeaning: 'Strength, courage, persuasion, influence, compassion.',
    reversedMeaning: 'Inner strength, self-doubt, low energy, raw emotion.',
    keywords: ['courage', 'patience', 'control', 'compassion'],
    element: 'fire',
    zodiacCorrespondence: 'Leo',
    image: buildImagePath(8, 'Strength', 'major', null),
    love: 'Gentle patience, emotional resilience, and taming conflict through warmth and grace.',
    career: 'Quiet confidence, persuasive leadership without aggression, and enduring project stamina.',
    finance: 'Resisting impulsive spending through steady discipline and inner composure.',
    spirituality: 'Transmuting lower instinctual desires into higher heart-centered consciousness.',
  },
  {
    id: 9,
    name: 'The Hermit',
    arcana: 'major',
    suit: null,
    number: 9,
    uprightMeaning: 'Soul-searching, introspection, being alone, inner guidance.',
    reversedMeaning: 'Isolation, loneliness, withdrawal, becoming a recluse.',
    keywords: ['solitude', 'meditation', 'reflection', 'wisdom'],
    element: 'earth',
    zodiacCorrespondence: 'Virgo',
    image: buildImagePath(9, 'The Hermit', 'major', null),
    love: 'Stepping back to reflect on relationship needs or valuing sacred personal autonomy.',
    career: 'Independent research, auditing strategic plans, and seeking wisdom from within.',
    finance: 'Prudent austerity, evaluating true essentials, and detaching from material hype.',
    spirituality: 'Solitary contemplation, holding your inner lantern, and deep spiritual enlightenment.',
  },
  {
    id: 10,
    name: 'Wheel of Fortune',
    arcana: 'major',
    suit: null,
    number: 10,
    uprightMeaning: 'Good luck, karma, life cycles, destiny, a turning point.',
    reversedMeaning: 'Bad luck, resistance to change, breaking cycles, setbacks.',
    keywords: ['fate', 'chance', 'change', 'karma'],
    element: 'fire',
    zodiacCorrespondence: 'Jupiter',
    image: buildImagePath(10, 'Wheel of Fortune', 'major', null),
    love: 'A serendipitous romantic encounter or a decisive, positive shift in an existing bond.',
    career: 'Sudden career breakthroughs, timely opportunities, and auspicious shifts in fortune.',
    finance: 'Unexpected windfall or favorable market turn; remember to save during upswings.',
    spirituality: 'Surrendering to the cosmic rhythm and understanding karmic cycles of cause and effect.',
  },
  {
    id: 11,
    name: 'Justice',
    arcana: 'major',
    suit: null,
    number: 11,
    uprightMeaning: 'Justice, fairness, truth, cause and effect, law.',
    reversedMeaning: 'Unfairness, lack of accountability, dishonesty, bias.',
    keywords: ['balance', 'karma', 'truth', 'fairness'],
    element: 'air',
    zodiacCorrespondence: 'Libra',
    image: buildImagePath(11, 'Justice', 'major', null),
    love: 'Fairness, mutual respect, resolution of disputes, and complete honesty in relationships.',
    career: 'Favorable legal or contract outcomes, transparent audits, and merit-based rewards.',
    finance: 'Balancing accounts, resolving debts, and maintaining strict ethical financial conduct.',
    spirituality: 'Recognizing karmic equilibrium and living in uncompromising harmony with universal truth.',
  },
  {
    id: 12,
    name: 'The Hanged Man',
    arcana: 'major',
    suit: null,
    number: 12,
    uprightMeaning: 'Pause, surrender, letting go, new perspectives.',
    reversedMeaning: 'Delays, resistance, stalling, indecision, martyrdom.',
    keywords: ['sacrifice', 'suspension', 'release', 'perspective'],
    element: 'water',
    zodiacCorrespondence: 'Neptune',
    image: buildImagePath(12, 'The Hanged Man', 'major', null),
    love: 'Pausing urgent demands, viewing love from a new lens, and practicing loving surrender.',
    career: 'A temporary plateau to re-evaluate priorities before the next major upward leap.',
    finance: 'Holding off on major purchases or investments while awaiting greater market clarity.',
    spirituality: 'Sacrificing the egoic agenda to receive profound spiritual illuminations.',
  },
  {
    id: 13,
    name: 'Death',
    arcana: 'major',
    suit: null,
    number: 13,
    uprightMeaning: 'Endings, change, transformation, transition, rebirth.',
    reversedMeaning: 'Resistance to change, personal transformation, lingering in the past.',
    keywords: ['rebirth', 'endings', 'new beginnings', 'transition'],
    element: 'water',
    zodiacCorrespondence: 'Scorpio',
    image: buildImagePath(13, 'Death', 'major', null),
    love: 'Releasing obsolete emotional patterns or closing a chapter to welcome transformative new love.',
    career: 'Exiting outdated career paths to step boldly into an authentic new professional calling.',
    finance: 'Restructuring financial assets, closing unprofitable accounts, and starting fresh.',
    spirituality: 'Ego-dissolution and emerging reborn from the chrysalis into higher conscious realization.',
  },
  {
    id: 14,
    name: 'Temperance',
    arcana: 'major',
    suit: null,
    number: 14,
    uprightMeaning: 'Balance, moderation, patience, purpose, alchemy.',
    reversedMeaning: 'Imbalance, excess, self-healing, re-alignment, impatience.',
    keywords: ['harmony', 'peace', 'alchemy', 'moderation'],
    element: 'fire',
    zodiacCorrespondence: 'Sagittarius',
    image: buildImagePath(14, 'Temperance', 'major', null),
    love: 'Equilibrium, gentle compromise, deep emotional healing, and enduring peace in partnership.',
    career: 'Harmonizing cross-functional teams, synthesizing diverse ideas, and steady project pacing.',
    finance: 'Balanced financial inflows and outflows with steady, measured wealth accumulation.',
    spirituality: 'Internal spiritual alchemy: Blending mind and soul into exquisite inner harmony.',
  },
  {
    id: 15,
    name: 'The Devil',
    arcana: 'major',
    suit: null,
    number: 15,
    uprightMeaning: 'Shadow self, attachment, addiction, restriction, materialism.',
    reversedMeaning: 'Releasing limiting beliefs, exploring dark thoughts, detachment, freedom.',
    keywords: ['bondage', 'materialism', 'temptation', 'shadow'],
    element: 'earth',
    zodiacCorrespondence: 'Capricorn',
    image: buildImagePath(15, 'The Devil', 'major', null),
    love: 'Beware of obsessive co-dependency, jealousy, or superficial physical attachments.',
    career: 'Recognizing golden handcuffs or toxic corporate cultures and planning your liberation.',
    finance: 'Avoiding predatory loans, reckless speculative gambles, or materialistic traps.',
    spirituality: 'Confronting your shadow self with compassionate awareness to dissolve unconscious bondage.',
  },
  {
    id: 16,
    name: 'The Tower',
    arcana: 'major',
    suit: null,
    number: 16,
    uprightMeaning: 'Sudden change, upheaval, chaos, revelation, awakening.',
    reversedMeaning: 'Personal transformation, fear of change, averting disaster.',
    keywords: ['disaster', 'destruction', 'revelation', 'breakthrough'],
    element: 'fire',
    zodiacCorrespondence: 'Mars',
    image: buildImagePath(16, 'The Tower', 'major', null),
    love: 'Sudden truth revealed that dismantles illusions, clearing space for genuine honesty.',
    career: 'Unexpected disruption of organizational structures; pivot rapidly and build on solid ground.',
    finance: 'Prepare emergency reserves for sudden expenses; steer clear of fragile high-risk schemes.',
    spirituality: 'A lightning-bolt epiphany that shatters limiting dogma and initiates authentic truth.',
  },
  {
    id: 17,
    name: 'The Star',
    arcana: 'major',
    suit: null,
    number: 17,
    uprightMeaning: 'Hope, faith, purpose, renewal, spirituality, inspiration.',
    reversedMeaning: 'Lack of faith, despair, self-trust, disconnection.',
    keywords: ['inspiration', 'healing', 'optimism', 'hope'],
    element: 'air',
    zodiacCorrespondence: 'Aquarius',
    image: buildImagePath(17, 'The Star', 'major', null),
    love: 'Healing of past emotional wounds, renewed romantic faith, and radiant optimism in love.',
    career: 'Inspiring vocational projects, creative breakthroughs, and long-term career aspirations fulfilling.',
    finance: 'Financial stability returning, with optimistic, sustainable future prospects.',
    spirituality: 'Deep connection to cosmic blessing, inner peace, and walking under celestial guidance.',
  },
  {
    id: 18,
    name: 'The Moon',
    arcana: 'major',
    suit: null,
    number: 18,
    uprightMeaning: 'Illusion, fear, anxiety, subconscious, intuition.',
    reversedMeaning: 'Release of fear, repressed emotion, inner confusion dissolving.',
    keywords: ['subconscious', 'dreams', 'secrets', 'illusion'],
    element: 'water',
    zodiacCorrespondence: 'Pisces',
    image: buildImagePath(18, 'The Moon', 'major', null),
    love: 'Unspoken emotional currents or misunderstandings; avoid jumping to conclusions without facts.',
    career: 'Navigate ambiguity with heightened intuition; verify all details before signing commitments.',
    finance: 'Hidden costs or deceptive financial schemes; ensure complete transparency before investing.',
    spirituality: 'Exploring the depths of the dream realm, psychic sensitivity, and subconscious healing.',
  },
  {
    id: 19,
    name: 'The Sun',
    arcana: 'major',
    suit: null,
    number: 19,
    uprightMeaning: 'Positivity, fun, warmth, success, vitality, joy.',
    reversedMeaning: 'Inner child, feeling down, overly optimistic, temporary delay.',
    keywords: ['joy', 'success', 'celebration', 'radiance'],
    element: 'fire',
    zodiacCorrespondence: 'Sun',
    image: buildImagePath(19, 'The Sun', 'major', null),
    love: 'Radiant romantic joy, profound mutual appreciation, and celebratory relationship milestones.',
    career: 'Outstanding public recognition, successful launches, and thriving career fulfillment.',
    finance: 'Abundant financial growth, flourishing investments, and well-earned material security.',
    spirituality: 'Radiating pure soul vitality, unconditional self-worth, and joyful cosmic alignment.',
  },
  {
    id: 20,
    name: 'Judgement',
    arcana: 'major',
    suit: null,
    number: 20,
    uprightMeaning: 'Judgement, rebirth, inner calling, absolution, awakening.',
    reversedMeaning: 'Self-doubt, inner critic, ignoring the call, hesitation.',
    keywords: ['reflection', 'awakening', 'redemption', 'calling'],
    element: 'fire',
    zodiacCorrespondence: 'Pluto',
    image: buildImagePath(20, 'Judgement', 'major', null),
    love: 'Forgiving past grievances, emotional resurrection, and making a definitive romantic commitment.',
    career: 'Heeding a profound vocational calling, rising to leadership, and reaching career milestones.',
    finance: 'Evaluating past financial decisions with clarity and making decisive course corrections.',
    spirituality: 'Hearing your soul’s higher trumpet call and stepping into your destined karmic purpose.',
  },
  {
    id: 21,
    name: 'The World',
    arcana: 'major',
    suit: null,
    number: 21,
    uprightMeaning: 'Completion, integration, accomplishment, travel, wholeness.',
    reversedMeaning: 'Seeking personal closure, short-cuts, delays, unfinished business.',
    keywords: ['fulfillment', 'harmony', 'wholeness', 'completion'],
    element: 'earth',
    zodiacCorrespondence: 'Saturn',
    image: buildImagePath(21, 'The World', 'major', null),
    love: 'Complete emotional fulfillment, global connections, and celebrating a harmonious milestone.',
    career: 'Culmination of a major long-term project, international success, and master-level achievement.',
    finance: 'Attaining long-term financial goals and enjoying a complete cycle of prosperity.',
    spirituality: 'Attaining holistic self-realization: The dance of the soul in complete unity with the cosmos.',
  },

  // 56 Minor Arcana (Wands, Cups, Swords, Pentacles)
  ...[
    // Wands
    { id: 22, name: 'Ace of Wands', suit: 'wands', num: 1, up: 'Inspiration, new opportunities, growth, potential.', rev: 'Emerging ideas, lack of direction.', kw: ['creation', 'willpower', 'spark'], el: 'fire' },
    { id: 23, name: 'Two of Wands', suit: 'wands', num: 2, up: 'Future planning, progress, decisions, discovery.', rev: 'Personal goals, unexpected delays.', kw: ['planning', 'decisions', 'vision'], el: 'fire' },
    { id: 24, name: 'Three of Wands', suit: 'wands', num: 3, up: 'Expansion, foresight, overseas opportunities.', rev: 'Playing small, lack of foresight.', kw: ['expansion', 'foresight', 'ventures'], el: 'fire' },
    { id: 25, name: 'Four of Wands', suit: 'wands', num: 4, up: 'Celebration, joy, harmony, relaxation, homecoming.', rev: 'Personal celebration, inner peace.', kw: ['celebration', 'harmony', 'homecoming'], el: 'fire' },
    { id: 26, name: 'Five of Wands', suit: 'wands', num: 5, up: 'Conflict, disagreements, competition, tension.', rev: 'Conflict avoidance, releasing tension.', kw: ['competition', 'debate', 'diversity'], el: 'fire' },
    { id: 27, name: 'Six of Wands', suit: 'wands', num: 6, up: 'Success, public recognition, progress, victory.', rev: 'Private achievement, ego check.', kw: ['victory', 'success', 'pride'], el: 'fire' },
    { id: 28, name: 'Seven of Wands', suit: 'wands', num: 7, up: 'Challenge, standing your ground, perseverance.', rev: 'Overwhelmed, exhausted, yielding.', kw: ['defense', 'perseverance', 'conviction'], el: 'fire' },
    { id: 29, name: 'Eight of Wands', suit: 'wands', num: 8, up: 'Rapid movement, swift action, alignment, messages.', rev: 'Delays, frustration, scattered focus.', kw: ['speed', 'action', 'momentum'], el: 'fire' },
    { id: 30, name: 'Nine of Wands', suit: 'wands', num: 9, up: 'Resilience, courage, persistence, final boundary.', rev: 'Exhaustion, defensiveness, fatigue.', kw: ['resilience', 'persistence', 'tenacity'], el: 'fire' },
    { id: 31, name: 'Ten of Wands', suit: 'wands', num: 10, up: 'Burden, extra responsibility, nearing completion.', rev: 'Delegation, releasing the load, burnout.', kw: ['burden', 'hard work', 'completion'], el: 'fire' },
    { id: 32, name: 'Page of Wands', suit: 'wands', num: 11, up: 'Creative sparks, exploration, spirited messages.', rev: 'Procrastination, scattered energy.', kw: ['enthusiasm', 'exploration', 'free spirit'], el: 'fire' },
    { id: 33, name: 'Knight of Wands', suit: 'wands', num: 12, up: 'Action, adventure, passion, charismatic drive.', rev: 'Impulsiveness, hasty errors, recklessness.', kw: ['passion', 'adventure', 'fearlessness'], el: 'fire' },
    { id: 34, name: 'Queen of Wands', suit: 'wands', num: 13, up: 'Warmth, courage, independence, vibrant charisma.', rev: 'Self-doubt, jealousy, introversion.', kw: ['confidence', 'warmth', 'determination'], el: 'fire' },
    { id: 35, name: 'King of Wands', suit: 'wands', num: 14, up: 'Visionary leadership, big picture thinking, honor.', rev: 'Impulsiveness, domineering expectations.', kw: ['leadership', 'vision', 'honor'], el: 'fire' },

    // Cups
    { id: 36, name: 'Ace of Cups', suit: 'cups', num: 1, up: 'Love, compassionate flow, intuition, new bond.', rev: 'Repressed emotion, self-compassion.', kw: ['new love', 'intuition', 'compassion'], el: 'water' },
    { id: 37, name: 'Two of Cups', suit: 'cups', num: 2, up: 'Unified love, mutual attraction, soul partnership.', rev: 'Disharmony, miscommunication, imbalance.', kw: ['partnership', 'attraction', 'connection'], el: 'water' },
    { id: 38, name: 'Three of Cups', suit: 'cups', num: 3, up: 'Celebration, friendship, creative collaboration.', rev: 'Independence, overindulgence, gossip.', kw: ['friendship', 'community', 'celebration'], el: 'water' },
    { id: 39, name: 'Four of Cups', suit: 'cups', num: 4, up: 'Meditation, contemplation, apathy, re-evaluation.', rev: 'Sudden awareness, seizing the moment.', kw: ['apathy', 'contemplation', 'introspection'], el: 'water' },
    { id: 40, name: 'Five of Cups', suit: 'cups', num: 5, up: 'Grief, regret, disappointment, spilled cups.', rev: 'Acceptance, self-forgiveness, moving forward.', kw: ['grief', 'regret', 'healing'], el: 'water' },
    { id: 41, name: 'Six of Cups', suit: 'cups', num: 6, up: 'Nostalgia, childhood memories, sweetness, gifts.', rev: 'Living in the past, childish behavior.', kw: ['nostalgia', 'memories', 'innocence'], el: 'water' },
    { id: 42, name: 'Seven of Cups', suit: 'cups', num: 7, up: 'Opportunities, imagination, choices, illusion.', rev: 'Clarity, aligning with real values.', kw: ['choices', 'illusions', 'fantasy'], el: 'water' },
    { id: 43, name: 'Eight of Cups', suit: 'cups', num: 8, up: 'Walking away, seeking higher truth, transition.', rev: 'Aimless drifting, fear of the unknown.', kw: ['departure', 'higher search', 'release'], el: 'water' },
    { id: 44, name: 'Nine of Cups', suit: 'cups', num: 9, up: 'Wishes fulfilled, satisfaction, gratitude, comfort.', rev: 'Smugness, materialism, dissatisfaction.', kw: ['contentment', 'gratitude', 'wish fulfilled'], el: 'water' },
    { id: 45, name: 'Ten of Cups', suit: 'cups', num: 10, up: 'Blissful harmony, family joy, emotional completion.', rev: 'Misaligned values, strained home ties.', kw: ['harmony', 'family bliss', 'fulfillment'], el: 'water' },
    { id: 46, name: 'Page of Cups', suit: 'cups', num: 11, up: 'Intuitive messages, creative flow, sensitivity.', rev: 'Emotional immaturity, creative block.', kw: ['curiosity', 'intuition', 'gentleness'], el: 'water' },
    { id: 47, name: 'Knight of Cups', suit: 'cups', num: 12, up: 'Romantic idealism, poetic charm, beauty, grace.', rev: 'Moodiness, overactive imagination.', kw: ['romance', 'charm', 'idealism'], el: 'water' },
    { id: 48, name: 'Queen of Cups', suit: 'cups', num: 13, up: 'Deep empathy, calm intuition, emotional healing.', rev: 'Self-care, codependency, feeling drained.', kw: ['compassion', 'calm', 'empathy'], el: 'water' },
    { id: 49, name: 'King of Cups', suit: 'cups', num: 14, up: 'Emotional balance, wisdom, diplomatic mastery.', rev: 'Inner balance, emotional volatility.', kw: ['diplomacy', 'composure', 'counsel'], el: 'water' },

    // Swords
    { id: 50, name: 'Ace of Swords', suit: 'swords', num: 1, up: 'Breakthrough, truth, mental clarity, precision.', rev: 'Clouded judgment, rethinking an idea.', kw: ['clarity', 'truth', 'vision'], el: 'air' },
    { id: 51, name: 'Two of Swords', suit: 'swords', num: 2, up: 'Difficult choices, stalemate, weighing options.', rev: 'Indecision, information overload.', kw: ['stalemate', 'choices', 'balance'], el: 'air' },
    { id: 52, name: 'Three of Swords', suit: 'swords', num: 3, up: 'Heartbreak, emotional release, truth cutting through.', rev: 'Releasing pain, forgiveness, healing.', kw: ['heartbreak', 'sorrow', 'release'], el: 'air' },
    { id: 53, name: 'Four of Swords', suit: 'swords', num: 4, up: 'Rest, restoration, meditation, quiet recovery.', rev: 'Burnout, stagnation, returning to action.', kw: ['rest', 'recuperation', 'sanctuary'], el: 'air' },
    { id: 54, name: 'Five of Swords', suit: 'swords', num: 5, up: 'Hollow victory, competition, conflict, ego clash.', rev: 'Reconciliation, amends, moving past pride.', kw: ['defeat', 'conflict', 'lessons learned'], el: 'air' },
    { id: 55, name: 'Six of Swords', suit: 'swords', num: 6, up: 'Transition, navigating calmer waters, recovery.', rev: 'Resistance to transition, baggage.', kw: ['transition', 'calmer seas', 'healing'], el: 'air' },
    { id: 56, name: 'Seven of Swords', suit: 'swords', num: 7, up: 'Strategy, discretion, navigating complex dynamics.', rev: 'Confessing secrets, imposter syndrome.', kw: ['strategy', 'resourcefulness', 'stealth'], el: 'air' },
    { id: 57, name: 'Eight of Swords', suit: 'swords', num: 8, up: 'Self-limiting thoughts, illusion of restriction.', rev: 'Releasing limiting beliefs, opening eyes.', kw: ['restriction', 'mindset', 'liberation'], el: 'air' },
    { id: 58, name: 'Nine of Swords', suit: 'swords', num: 9, up: 'Worry, anxiety, nighttime fears, mental loops.', rev: 'Releasing worry, seeking support.', kw: ['anxiety', 'mental loop', 'clarity dawn'], el: 'air' },
    { id: 59, name: 'Ten of Swords', suit: 'swords', num: 10, up: 'Final ending, rock bottom, sunrise on the horizon.', rev: 'Regeneration, recovery, resisting the end.', kw: ['closure', 'rock bottom', 'new dawn'], el: 'air' },
    { id: 60, name: 'Page of Swords', suit: 'swords', num: 11, up: 'Curiosity, sharp intellect, active inquiry.', rev: 'All talk no action, haste, cynicism.', kw: ['curiosity', 'inquiry', 'mental speed'], el: 'air' },
    { id: 61, name: 'Knight of Swords', suit: 'swords', num: 12, up: 'Direct action, ambition, decisive execution.', rev: 'Restless haste, burnout, impulsive words.', kw: ['decisive', 'driven', 'bold'], el: 'air' },
    { id: 62, name: 'Queen of Swords', suit: 'swords', num: 13, up: 'Independent intellect, clear boundaries, truth.', rev: 'Coldness, bitterness, overly critical.', kw: ['boundaries', 'clarity', 'discernment'], el: 'air' },
    { id: 63, name: 'King of Swords', suit: 'swords', num: 14, up: 'Intellectual authority, fair judgment, mastery.', rev: 'Misuse of authority, rigid dogma.', kw: ['authority', 'truth', 'reasoning'], el: 'air' },

    // Pentacles
    { id: 64, name: 'Ace of Pentacles', suit: 'pentacles', num: 1, up: 'Material opportunity, manifestation, seed of wealth.', rev: 'Missed opportunity, poor financial planning.', kw: ['opportunity', 'prosperity', 'foundation'], el: 'earth' },
    { id: 65, name: 'Two of Pentacles', suit: 'pentacles', num: 2, up: 'Balance, adaptability, juggling resources, flow.', rev: 'Disorganization, financial overwhelm.', kw: ['balance', 'prioritization', 'adaptability'], el: 'earth' },
    { id: 66, name: 'Three of Pentacles', suit: 'pentacles', num: 3, up: 'Teamwork, master craftsmanship, collaboration.', rev: 'Friction in team, subpar work.', kw: ['collaboration', 'skill', 'craft'], el: 'earth' },
    { id: 67, name: 'Four of Pentacles', suit: 'pentacles', num: 4, up: 'Security, saving, stability, protecting assets.', rev: 'Greed, financial insecurity, hoarding.', kw: ['security', 'conservatism', 'saving'], el: 'earth' },
    { id: 68, name: 'Five of Pentacles', suit: 'pentacles', num: 5, up: 'Temporary hardship, isolation, seek sanctuary.', rev: 'Financial recovery, rebuilding resources.', kw: ['resilience', 'sanctuary', 'recovery'], el: 'earth' },
    { id: 69, name: 'Six of Pentacles', suit: 'pentacles', num: 6, up: 'Generosity, balanced giving and receiving, charity.', rev: 'One-sided arrangements, debt repayment.', kw: ['generosity', 'sharing', 'balance'], el: 'earth' },
    { id: 70, name: 'Seven of Pentacles', suit: 'pentacles', num: 7, up: 'Patience, long-term investments, evaluating growth.', rev: 'Impatience, questioning returns.', kw: ['patience', 'cultivation', 'harvest'], el: 'earth' },
    { id: 71, name: 'Eight of Pentacles', suit: 'pentacles', num: 8, up: 'Dedicated practice, skill mastery, craftsmanship.', rev: 'Perfectionism, misdirected effort.', kw: ['apprenticeship', 'mastery', 'precision'], el: 'earth' },
    { id: 72, name: 'Nine of Pentacles', suit: 'pentacles', num: 9, up: 'Abundance, self-sufficiency, refined elegance.', rev: 'Overworking, financial dependency.', kw: ['luxury', 'self-sufficiency', 'grace'], el: 'earth' },
    { id: 73, name: 'Ten of Pentacles', suit: 'pentacles', num: 10, up: 'Generational wealth, family legacy, long-term success.', rev: 'Financial disputes, family inheritance issues.', kw: ['legacy', 'wealth', 'family'], el: 'earth' },
    { id: 74, name: 'Page of Pentacles', suit: 'pentacles', num: 11, up: 'New financial skill, goal-setting, practical ideas.', rev: 'Procrastination, unrealistic schemes.', kw: ['diligence', 'practicality', 'learning'], el: 'earth' },
    { id: 75, name: 'Knight of Pentacles', suit: 'pentacles', num: 12, up: 'Reliability, methodical routine, steadfast loyalty.', rev: 'Stubbornness, boredom, perfectionism.', kw: ['steadfast', 'methodical', 'reliable'], el: 'earth' },
    { id: 76, name: 'Queen of Pentacles', suit: 'pentacles', num: 13, up: 'Nurturing abundance, practical care, warm hearth.', rev: 'Work-life imbalance, financial anxiety.', kw: ['nurturing', 'abundance', 'hospitality'], el: 'earth' },
    { id: 77, name: 'King of Pentacles', suit: 'pentacles', num: 14, up: 'Financial mastery, enterprise leadership, stability.', rev: 'Material obsession, stubborn rigidity.', kw: ['enterprise', 'prosperity', 'stability'], el: 'earth' },
  ].map((c) => ({
    id: c.id,
    name: c.name,
    arcana: 'minor' as const,
    suit: c.suit as 'wands' | 'cups' | 'swords' | 'pentacles',
    number: c.num,
    uprightMeaning: c.up,
    reversedMeaning: c.rev,
    keywords: c.kw,
    element: c.el as 'fire' | 'water' | 'air' | 'earth',
    zodiacCorrespondence: null,
    image: buildImagePath(c.id, c.name, 'minor', c.suit),
    love: `${c.up} In relationships, this brings practical, grounded alignment.`,
    career: `${c.up} In career matters, steady discipline yields high dividends.`,
    finance: `Prudent financial management and aligned investments are favored.`,
    spirituality: `Grounding spiritual insights into practical, everyday living.`,
  }))
];
